# version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports: 
      - "6379:6379"
    volumes:
      - redis_data:/data
    
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: talentsieve
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  qdrant:
    image: qdrant/qdrant:v1.15.1
    ports: 
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      
  api:
    build: .
    command: npm start
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./uploads:/app/uploads
    ports: 
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - UPLOAD_DIR=/app/uploads
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/talentsieve
      - REDIS_URL=redis://redis:6379
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      qdrant:
        condition: service_started
        
  worker:
    build: .
    command: npm run worker
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - UPLOAD_DIR=/app/uploads
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/talentsieve
      - REDIS_URL=redis://redis:6379
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      qdrant:
        condition: service_started

volumes:
  postgres_data:
  redis_data:
  qdrant_data: